version: '3'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: minio    #管理后台用户名
      MINIO_SECRET_KEY: minio123 #管理后台密码，最小8个字符
    volumes:
      - ./data:/data               #映射当前目录下的data目录至容器内/data目录
      # - /docker/minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    networks:
      - my
    # privileged: true
    # restart: always

  # minio1:
  #   image: minio/minio
  #   hostname: minio1
  #   volumes:
  #     - ./data1-1:/data1
  #     - ./data1-2:/data2
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - my
  #
  # minio2:
  #   image: minio/minio
  #   hostname: minio2
  #   volumes:
  #     - ./data2-1:/data1
  #     - ./data2-2:/data2
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - my

  # minio3:
  #   image: minio/minio
  #   hostname: minio3
  #   volumes:
  #     - ./data3-1:/data1
  #     - ./data3-2:/data2
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - my

  # minio4:
  #   image: minio/minio
  #   hostname: minio4
  #   volumes:
  #     - ./data4-1:/data1
  #     - ./data4-2:/data2
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - my
networks:
  my:
    external:
      name: my

  # nginx:
  #   image: nginx:1.19.2-alpine
  #   hostname: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   depends_on:
  #     - minio1
  #     - minio2
  #     - minio3
  #     - minio4
